name: ci 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        name: checkout code 📥
      - name: install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "pnpm"
      - name: install dependencies 🔧
        run: pnpm install
      - name: build ✅
        run: pnpm build
      - name: test ✅
        run: pnpm test
      - name: routes ✅
        run: pnpm pls routes
      - name: doctor ✅
        run: pnpm pls doctor
      - name: generate migration ✅
        run: pnpm migrate foobar
      - name: run migration ✅
        run: pnpm migrate
      - name: seed ✅
        run: pnpm pls seed
      # TODO write mailer, write command, run command, assert shell output
      # TODO write scheduler, write command, run command, assert shell output, periodic counter 
      # TODO write job, write command, run command, assert shell output
      # TODO pnpm dev to start server, wait 5 seconds, curl localhost:3000/health, assert status 200
      




