name: ci 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      NODE_ENV: development
      PORT: 3000
      DB_URL: data.db
      SMTP_HOST: smtp.example.com
      SMTP_USER: user@example.com
      SMTP_PASS: password
    steps:
      - uses: actions/checkout@v4
        name: checkout code 📥
      - name: install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "pnpm"
      - name: install dependencies 🔧
        run: pnpm install
      - name: build ✅
        run: pnpm build
      - name: test ✅
        run: pnpm test
      - name: routes ✅
        run: pnpm pls routes
      - name: doctor ✅
        run: pnpm pls doctor
      - name: generate migration ✅
        run: pnpm migrate foobar
      - name: run migration ✅
        run: pnpm migrate
      - name: seed ✅
        run: pnpm pls seed
      - name: 200 ok ✅
        run: |
          pnpm dev &
          sleep 10  # Wait for the server to start
          if curl -s http://localhost:3000 | grep -q "{\"status\":\"ok\"}"; then
            echo "Server started successfully and contains 'Let's go'"
          else
            echo "Server check failed"
            exit 1
          fi
          kill $!  # Stop the server
      # TODO write mailer, write command, run command, assert shell output
      # TODO write scheduler, write command, run command, assert shell output, periodic counter
      # TODO write job, write command, run command, assert shell output
      # TODO pnpm dev to start server, wait 5 seconds, curl localhost:3000/health, assert status 200
